# Generated by Django 4.2.17 on 2024-12-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_city', models.CharField(max_length=100)),
                ('emp_phone', models.BigIntegerField()),
            ],
        ),
    ]
