# Generated by Django 4.2.17 on 2025-01-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_intern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='intern_phone',
            field=models.CharField(max_length=10),
        ),
    ]
