# Generated by Django 4.2.17 on 2025-01-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
