# Generated by Django 4.2.17 on 2025-01-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_monitor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
