# Generated by Django 4.2.18 on 2025-01-16 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='passby',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
